package com.junvu.common;

public class LocatorsCSM {
    public static String headerLogin = "//h1[normalize-space()='Welcome to Active eCommerce CMS']";
    public static String inputEmail = "//input[@id='email']";
    public static String inputPassword = "//input[@id='password']";
    public static String buttonLogin = "//button[@type='submit']";
    public static String menuDashboard = "//span[normalize-space()='Dashboard']";
    public static String menuProduct = "//ul[@id='main-menu']/descendant::span[normalize-space()='Products']";
    public static String menuCategory = "//ul[@id='main-menu']/descendant::a[@href='https://cms.anhtester.com/admin/categories']";
    public static String headerCategory = "//h1[normalize-space()='All categories']";
    public static String buttonCreateCategory = "//a[@href='https://cms.anhtester.com/admin/categories/create']";
    public static String headerAddNewCategory = "//h5[normalize-space()='Category Information']";
    public static String textBoxName = "//input[@id='name']";
    public static String dropListParentCategory = "//select[@name='parent_id']/following-sibling::button";
    public static String parentCategorySearch = "//select[@name='parent_id']/following-sibling::div//input";
    public static String textBoxOrderNumber = "//div/input[@id='order_level']";
    public static String dropListType = "//select[@name='digital']/following-sibling::button";
    public static String bannerImage = "(//div/label[@for='signinSrEmail']/following-sibling::div//div[normalize-space()='Browse'])[1]";
    public static String bannerImageAddFile = "//div//button[normalize-space()='Add Files']";
    public static String iconImage = "(//div/label[@for='signinSrEmail']/following-sibling::div//div[normalize-space()='Browse'])[3]";
    public static String iconImageAddFile = "//div//button[normalize-space()='Add Files']";
    public static String metaTitleTextbox = "//div/label[normalize-space()='Meta Title']/following-sibling::div/input";
    public static String metaDescription = "//div/textarea[@name='meta_description']";
    public static String dropListFilteringAttributes = "//select[@name='filtering_attributes[]']/following-sibling::button";
    public static String saveButton = "//div/button[@type='submit']";
    public static String addSuccessMessage = "//span[normalize-space()='Category has been inserted successfully']";
    public static String buttonEditCategory = "(//a[contains(@href,'https://cms.anhtester.com/admin/categories/edit/')])[1]";
    public static String editSuccessMessage = "//div/span[normalize-space()='Category has been updated successfully']";
    public static String buttonDeleteCategory = "(//a[contains(@data-href,'https://cms.anhtester.com/admin/categories/destroy/')])[1]";
    public static String deleteSuccessMessage = "//div/span[normalize-space()='Category has been deleted successfully']";
    public static String addNewProduct = "//span[normalize-space()='Add New Product']";
    public static String productNamefield = "//input[@placeholder='Product Name']";
    public static String productCategory = "//button[@data-id='category_id']";
    public static String productCategoryTextBox = "(//input[@type='search'])[1]";
    public static String brandDropList = "//button[@data-id='brand_id']";
    public static String brandTextBox = "(//input[@type='search'])[2]";
    public static String unitField = "//input[@placeholder='Unit (e.g. KG, Pc etc)']";
    public static String weightField = "//input[@placeholder='0.00']";
    public static String minQuantityPur = "//input[@name='min_qty']";
    public static String productTags = "//tags[@role='tagslist']";
    public static String productBarcode = "//input[@placeholder='Barcode']";
    public static String productGalleryImages = "(//div[@data-type = 'image']/descendant::div//div)[1]";
    public static String productThumnailImage = "(//div[@data-type = 'image']/descendant::div//div)[2]";
    public static String productVariationHeader = "//h5[normalize-space()='Product Variation']";
    public static String productColorsEnableButton = "//input[@name='colors_active']";
    public static String productColors = "//button[@data-id='colors']";
    public static String productColorsSearch = "(//input[@type='search'])[3]";
    public static String productColor_1 = "(//div[@id='bs-select-4']//ul[@role='presentation']/li)[1]";
    public static String productColor_2 = "(//div[@id='bs-select-4']//ul[@role='presentation']/li)[2]";
    public static String productColor_3 = "(//div[@id='bs-select-4']//ul[@role='presentation']/li)[3]";
    public static String productColor_4 = "(//div[@id='bs-select-4']//ul[@role='presentation']/li)[4]";
    public static String productColor_5 = "(//div[@id='bs-select-4']//ul[@role='presentation']/li)[4]";
    public static String productAttributes = "//button[@data-id='choice_attributes']";
    public static String productAtributes_Size = "//div[@id='customer_choice_options']//div[@class='col-md-8']//button";
    public static String productPriceandStockheader = "//h5[normalize-space()='Product price + stock']";
    public static String productPriceField = "//input[@placeholder='Unit price']";
    public static String productDiscountDateRange = "//input[@placeholder='Select Date']";
    public static String productDiscountDateSelectButton = "//div[@class='drp-buttons']/button[@type='button'][normalize-space()='Select']";
    public static String productDiscountField = "//input[@placeholder='Discount']";
    public static String productDiscountDropList = "//select[@name='discount_type']/following-sibling::button";
    public static String productQuantityField = "//input[@placeholder='Quantity']";
    public static String productSKU = "//input[@placeholder='SKU']";
    public static String productDescriptionheader = "//h5[normalize-space()='Product Description']";
    public static String productDescription = "//div[@role='textbox']/p";
    public static String productSEOMetaTagsheader = "//h5[normalize-space()='SEO Meta Tags']";
    public static String productSaveAndPublishButton = "//button[normalize-space()='Save & Publish']";
    public static String addProductSuccessMessage = "//button/span[normalize-space(),'Product has been inserted successfully']";
}
